; CC2 - Development Environment
; slothbear - BenzWorld.org
; ESP32 - uLisp
; WORK IN PROGRESS

(defvar VACPIN1 2)
(defvar VACPIN2 3)
(defvar VACPIN3 4)

(defvar RECIRCP 5)
(defvar RECIRCL 6)
(defvar COOLANTP 7)

(defvar BLOWER1 8)
(defvar BLOWER2 9)
(defvar BLOWER3 10)


(defun heat ()
    (digialwrite COOLANTP t))
(defun cool ()
    (digialwrite COOLANTP nil))
(defun blower ())

; Pins are not mapped to real soldenoids yet
; Used for baseline testing
(defun defrost ()
    (format t "HI")
    (digialwrite VACPIN1 nil)
    (digialwrite VACPIN2 nil)
    (digialwrite VACPIN3 nil))
(defun hi ()
    (format t "HI")
    (digialwrite VACPIN1 nil)
    (digialwrite VACPIN2 t)
    (digialwrite VACPIN3 t))
(defun lo ()
    (format t "LO")
    (digialwrite VACPIN1 t)
    (digialwrite VACPIN2 nil)
    (digialwrite VACPIN3 t))
(defun bi-level ()
    (format t "BI-LEVEL")
    (digialwrite VACPIN1 nil)
    (digialwrite VACPIN2 nil)
    (digialwrite VACPIN3 t))
(defun auto ()
    (format t "AUTOMATIC")
    (digialwrite VACPIN1 t)
    (digialwrite VACPIN2 t)
    (digialwrite VACPIN3 t))

(defun self-test ()
    (format t "TESTING FUNCTIONALITY")
    (hi)
    (delay 4000)
    (lo)
    (delay 4000)
    (bi-level)
    (delay 4000)
    (auto)
    (delay 4000))

(defun init ()
    (format t "INIT")
    (digialwrite COOLANTP nil)
    (digialwrite VACPIN1 nil)
    (digialwrite VACPIN2 nil)
    (digialwrite VACPIN3 nil)
    (pinmode 2 t)
    (pinmode 3 t)
    (pinmode 4 t)
    (pinmode 5 t)
    (pinmode 6 t)
    (pinmode 7 t)
    (pinmode 8 t)
    (pinmode 9 t)
    (pinmode 9 t)
    )

(init)