; CC2 - Development Environment
; slothbear - BenzWorld.org
; ESP32 - uLisp
; WORK IN PROGRESS

(defvar VACPIN1 2)
(defvar VACPIN2 3)
(defvar VACPIN3 4)

(defvar RECIRCP 5)
(defvar RECIRCL 6)
(defvar COOLANTP 7)

(defvar BLOWER1 8)
(defvar BLOWER2 9)
(defvar BLOWER3 10)


(defun heat ()
    (digitalwrite COOLANTP t))
(defun cool ()
    (digitalwrite COOLANTP nil))
(defun blower ())

; Pins are not mapped to real soldenoids yet
; Used for baseline testing
(defun defrost ()
    (format t "HI")
    (digitalwrite VACPIN1 nil)
    (digitalwrite VACPIN2 nil)
    (digitalwrite VACPIN3 nil))
(defun hi ()
    (format t "HI")
    (digitalwrite VACPIN1 nil)
    (digitalwrite VACPIN2 t)
    (digitalwrite VACPIN3 t))
(defun lo ()
    (format t "LO")
    (digitalwrite VACPIN1 t)
    (digitalwrite VACPIN2 nil)
    (digitalwrite VACPIN3 t))
(defun bi-level ()
    (format t "BI-LEVEL")
    (digitalwrite VACPIN1 nil)
    (digitalwrite VACPIN2 nil)
    (digitalwrite VACPIN3 t))
(defun auto ()
    (format t "AUTOMATIC")
    (digitalwrite VACPIN1 t)
    (digitalwrite VACPIN2 t)
    (digitalwrite VACPIN3 t))

(defun self-test ()
    (format t "TESTING FUNCTIONALITY")
    (hi)
    (delay 4000)
    (lo)
    (delay 4000)
    (bi-level)
    (delay 4000)
    (auto)
    (delay 4000))

(defun init ()
    (format t "INIT")
    (digitalwrite COOLANTP nil)
    (digitalwrite VACPIN1 nil)
    (digitalwrite VACPIN2 nil)
    (digitalwrite VACPIN3 nil)
    (pinmode 2 t)
    (pinmode 3 t)
    (pinmode 4 t)
    (pinmode 5 t)
    (pinmode 6 t)
    (pinmode 7 t)
    (pinmode 8 t)
    (pinmode 9 t)
    (pinmode 10 t))

(init)